#ifndef QNOVA_TOKEN_H
#define QNOVA_TOKEN_H

#include <stddef.h>

typedef enum {
    QNOVA_TOKEN_EOF = 0,
    QNOVA_TOKEN_NEWLINE,
    QNOVA_TOKEN_SEMICOLON,

    QNOVA_TOKEN_IDENTIFIER,
    QNOVA_TOKEN_INTEGER,
    QNOVA_TOKEN_REAL,
    QNOVA_TOKEN_STRING,

    QNOVA_TOKEN_KW_LET,
    QNOVA_TOKEN_KW_FN,
    QNOVA_TOKEN_KW_RETURN,
    QNOVA_TOKEN_KW_EMIT,
    QNOVA_TOKEN_KW_WHEN,
    QNOVA_TOKEN_KW_ELSE,
    QNOVA_TOKEN_KW_REPEAT,
    QNOVA_TOKEN_KW_GUARD,
    QNOVA_TOKEN_KW_OBSERVE,
    QNOVA_TOKEN_KW_SIMULATE,
    QNOVA_TOKEN_KW_PATCH,

    QNOVA_TOKEN_KW_QBIT,
    QNOVA_TOKEN_KW_H,
    QNOVA_TOKEN_KW_X,
    QNOVA_TOKEN_KW_Z,
    QNOVA_TOKEN_KW_CNOT,
    QNOVA_TOKEN_KW_MEASURE,
    QNOVA_TOKEN_KW_RESET,
    QNOVA_TOKEN_KW_PROBS,

    QNOVA_TOKEN_KW_TRUE,
    QNOVA_TOKEN_KW_FALSE,
    QNOVA_TOKEN_KW_AND,
    QNOVA_TOKEN_KW_OR,
    QNOVA_TOKEN_KW_NOT,

    QNOVA_TOKEN_KW_INT,
    QNOVA_TOKEN_KW_REAL,
    QNOVA_TOKEN_KW_BOOL,
    QNOVA_TOKEN_KW_STRING,
    QNOVA_TOKEN_KW_BIT,
    QNOVA_TOKEN_KW_UNIT,

    QNOVA_TOKEN_LEFT_PAREN,
    QNOVA_TOKEN_RIGHT_PAREN,
    QNOVA_TOKEN_LEFT_BRACE,
    QNOVA_TOKEN_RIGHT_BRACE,
    QNOVA_TOKEN_COMMA,
    QNOVA_TOKEN_COLON,

    QNOVA_TOKEN_ARROW,
    QNOVA_TOKEN_ASSIGN,
    QNOVA_TOKEN_EQUAL,
    QNOVA_TOKEN_NOT_EQUAL,
    QNOVA_TOKEN_LESS,
    QNOVA_TOKEN_LESS_EQUAL,
    QNOVA_TOKEN_GREATER,
    QNOVA_TOKEN_GREATER_EQUAL,

    QNOVA_TOKEN_PLUS,
    QNOVA_TOKEN_MINUS,
    QNOVA_TOKEN_STAR,
    QNOVA_TOKEN_SLASH,
    QNOVA_TOKEN_PERCENT,

    QNOVA_TOKEN_KET_ZERO,
    QNOVA_TOKEN_KET_ONE,

    QNOVA_TOKEN_KIND_COUNT
} qnova_token_kind_t;

typedef struct {
    qnova_token_kind_t kind;
    size_t byte_offset;
    size_t byte_length;
    size_t line;
    size_t column;
} qnova_token_t;

const char *qnova_token_kind_name(qnova_token_kind_t kind);

int qnova_token_is_valid(const qnova_token_t *token);

#endif
